{ 
  '0': { a: { path: 'a', content: 'b' } }, 
  '1': { a: { path: 'a', content: 'b', locals: { a: 'a' } } }, 
  '2': { a: { path: 'a', content: 'b', locals: { a: 'a' } } }, 
  '3': { a: { path: 'a', content: 'this is content' } }, 
  '4': { a: { path: 'a', content: 'A above\n{{body}}\nA below', locals: { layout: 'b' } } }, 
  '5': { a: { path: 'a', content: 'this is content', locals: { layout: 'b' } } }, 
  '6': { a: { path: 'a', content: 'This is content.', options: { ext: '.foo' } } }, 
  '7': { a: { path: 'a', content: 'This is content.', options: { ext: '.foo' } } }, 
  '8': { 'a.md': { path: 'a.md', content: 'b', ext: '.md' } }, 
  '9': { 'a.md': { path: 'a.md', content: 'c', ext: '.md' } }, 
  '10': { 'a/b/c.md': { path: 'a/b/c.md', content: 'this is content.', locals: { a: 'b' }, options: { y: 'z' }, ext: '.md' } }, 
  '11': { 'a/b/c.md': { path: 'a/b/c.md', content: 'this is content.', locals: { a: 'b' }, options: { y: 'z' }, ext: '.md' } }, 
  '12': { 'a/b/c.md': { path: 'a/b/c.md', content: 'this is content.', locals: { a: 'b' }, ext: '.md' } }, 
  '13': { 'a/b/c.md': { path: 'a/b/c.md', content: 'this is content.', locals: { a: 'b' }, options: { y: 'z' }, ext: '.md' } }, 
  '14': { 'a/b/c.md': { path: 'a/b/c.md', content: 'this is content.', locals: { a: 'b' }, ext: '.md' } }, 
  '15': { 'a/b/c.md': { path: 'a/b/c.md', content: 'this is content.', ext: '.md' } }, 
  '16': { 'a/b/c.md': { path: 'a/b/c.md', content: 'this is baz', locals: { a: 'b' }, options: { foo: 'bar', bar: 'baz' }, ext: '.md' } }, 
  '17': { 'a/b/c.md': { path: 'a/b/c.md', content: 'this is content.', locals: { a: 'b' }, options: { y: 'z' }, ext: '.md' } }, 
  '18': { 'a/b/c.md': { path: 'a/b/c.md', content: 'this is content.', locals: { a: 'b' }, options: { y: 'z' }, ext: '.md' } }, 
  '19': { 'a/b/c.md': { path: 'a/b/c.md', content: 'this is content.', locals: { a: 'b' }, options: { y: 'z' }, ext: '.md' } }, 
  '20': { 'a/b/c.md': { path: 'a/b/c.md', content: 'this is content.', locals: { a: 'b' }, ext: '.md' } }, 
  '21': { 'a/b/c.md': { path: 'a/b/c.md', content: 'this is content.', locals: { a: 'b' }, options: { y: 'z' }, ext: '.md' } }, 
  '22': { 'a/b/c.md': { path: 'a/b/c.md', content: 'this is content.', locals: { a: 'b' }, ext: '.md' } }, 
  '23': { 'a/b/c.md': { path: 'a/b/c.md', content: 'this is content.', ext: '.md' } }, 
  '24': { abc: { path: 'abc', content: '<%= wrap(include("content.tmpl")) %> This is a page!' } }, 
  '25': { 'abc.md': { path: 'abc.md', content: 'This is content.', locals: { a: 'b' }, options: { c: 'd' }, ext: '.md' } }, 
  '26': { 'abc.md': { path: 'abc.md', content: 'This is content.', locals: { a: 'b', c: 'd' }, ext: '.md' } }, 
  '27': { 'abc.md': { path: 'abc.md', content: 'This is content.', locals: { name: 'Jon Schlinkert' }, ext: '.md' } }, 
  '28': { 'abc.md': { path: 'abc.md', content: 'This is content.', ext: '.md' } }, 
  '29': {}, 
  '30': { foo: { path: 'foo', content: 'this is content.', locals: { a: 'b' }, options: { fez: 'foo' } } }, 
  '31': { foo: { path: 'foo', content: 'this is content.' } }, 
  '32': { 'foo/bar/abc.md': { path: 'foo/bar/abc.md', content: 'This is content.', locals: { a: 'b' }, options: { c: 'd' }, ext: '.md' } }, 
  '33': { 'foo/bar/abc.md': { path: 'foo/bar/abc.md', content: 'This is content.', locals: { a: 'b' }, ext: '.md' } }, 
  '34': { 'foo/bar/abc.md': { path: 'foo/bar/abc.md', content: 'This is content.', ext: '.md' } }, 
  '35': { 'foo1.md': { path: 'foo1.md', content: 'This is content', locals: { name: 'Jon Schlinkert' }, ext: '.md' } }, 
  '36': { 'test/fixtures/layouts/c.txt': { path: 'test/fixtures/layouts/c.txt', content: '---\ntitle: CCC\n---\nThis is fixture c.md', locals: { name: 'Brian Woodward' }, options: { cwd: '/Users/jonschlinkert/dev/loaders/load-templates/test/fixtures', name: [Function] }, ext: '.txt' }, 'test/fixtures/layouts/b.txt': { path: 'test/fixtures/layouts/b.txt', content: '---\ntitle: BBB\n---\nThis is fixture b.txt', locals: { name: 'Brian Woodward' }, options: { cwd: '/Users/jonschlinkert/dev/loaders/load-templates/test/fixtures', name: [Function] }, ext: '.txt' }, 'test/fixtures/layouts/a.txt': { path: 'test/fixtures/layouts/a.txt', content: '---\ntitle: AAA\n---\nThis is fixture a.txt', locals: { name: 'Brian Woodward' }, options: { cwd: '/Users/jonschlinkert/dev/loaders/load-templates/test/fixtures', name: [Function] }, ext: '.txt' } }, 
  '37': { 'pages/a.md': { path: 'pages/a.md', content: 'This is content.', locals: { name: 'Jon Schlinkert' }, ext: '.md' } }, 
  '38': {}, 
  '39': {}, 
  '40': {}, 
  '41': {}, 
  '42': {}, 
  '43': {}, 
  '44': {}, 
  '45': { 'test/fixtures/a.md': { path: 'test/fixtures/a.md', content: '---\ntitle: AAA\n---\nThis is fixture a.md', locals: { a: 'b' }, options: { something: true }, ext: '.md' } }, 
  '46': { 'test/fixtures/a.md': { path: 'test/fixtures/a.md', content: '---\ntitle: AAA\n---\nThis is fixture a.md', locals: { a: 'b' }, ext: '.md' } }, 
  '47': { 'test/fixtures/a.md': { path: 'test/fixtures/a.md', content: '---\ntitle: AAA\n---\nThis is fixture a.md', locals: { foo: 'bar' }, ext: '.md' } }, 
  '48': { 'test/fixtures/a.md': { path: 'test/fixtures/a.md', content: '---\ntitle: AAA\n---\nThis is fixture a.md', ext: '.md' } }, 
  '49': { 'test/fixtures/a.txt': { path: 'test/fixtures/a.txt', content: '---\ntitle: AAA\n---\nThis is from a.txt.', locals: { a: 'b' }, options: { foo: true }, ext: '.txt' } }, 
  '50': { 'test/fixtures/one/a.md': { path: 'test/fixtures/one/a.md', content: '---\ntitle: A\n---\n\nThis is {{title}}', locals: { name: 'Brian Woodward' }, ext: '.md' } }, 
  '51': { 'test/fixtures/one/a.md': { path: 'test/fixtures/one/a.md', content: '---\ntitle: A\n---\n\nThis is {{title}}', ext: '.md' } }, 
  '52': {}, 
  '53': {}, 
  '54': {}, 
  '55': {}, 
  '56': {}, 
  '57': {}, 
  '58': {}, 
  '59': {}, 
  '60': {}, 
  '61': {}, 
  '62': { 'a/b/c.md': { content: 'this is content.', locals: { a: 'b' }, options: { y: 'z' }, path: 'a/b/c.md', ext: '.md' } }, 
  '63': { 'a/b/c.md': { content: 'this is content.', locals: { a: 'b' }, path: 'a/b/c.md', ext: '.md' } }, 
  '64': { 'a/b/c.md': { content: 'this is content.', locals: { a: 'b' }, options: { y: 'z' }, path: 'a/b/c.md', ext: '.md' } }, 
  '65': { 'a/b/c.md': { content: 'this is content.', locals: { a: 'b' }, path: 'a/b/c.md', ext: '.md' } }, 
  '66': { 'a/b/c.md': { content: 'this is content.', path: 'a/b/c.md', ext: '.md' } }, 
  '67': { foo: { content: 'this is content.', locals: { fez: 'foo', a: 'b' }, path: 'foo' } }, 
  '68': { 'foo/bar.md': { content: 'this is content.', data: { a: 'a' }, path: 'foo/bar.md', ext: '.md' } }, 
  '69': { 'foo/bar.md': { content: 'this is content.', locals: { foo: 'bar' }, path: 'foo/bar.md', ext: '.md' } }, 
  '70': { 'foo/bar.md': { content: 'this is content.', path: 'foo/bar.md', ext: '.md' } }, 
  '71': { a: { content: 'A above\n{{body}}\nA below', locals: { layout: 'b' }, path: 'a' } }, 
  '72': { a: { content: 'A above\n{{body}}\nA below', locals: { layout: 'b' }, path: 'a' } }, 
  '73': { b: { content: 'B above\n{{body}}\nB below', locals: { layout: 'c' }, path: 'b' } }, 
  '74': { c: { content: 'C above\n{{body}}\nC below', locals: { layout: 'd' }, path: 'c' } }, 
  '75': { 'a/b/c.md': { path: 'a/b/c.md', content: 'this is content.', locals: { c: 'd', a: 'b' }, options: { e: 'f', y: 'z' }, ext: '.md' } }, 
  '76': { 'a/b/c.md': { path: 'a/b/c.md', content: 'this is content.', locals: { a: 'b' }, options: { y: 'z' }, ext: '.md' } }, 
  '77': { 'a/b/c.md': { path: 'a/b/c.md', content: 'this is content.', locals: { a: 'b' }, ext: '.md' } }, 
  '78': { 'a/b/c.md': { path: 'a/b/c.md', content: 'this is content.', locals: { a: 'b' }, options: { y: 'z' }, ext: '.md' } }, 
  '79': { 'a/b/c.md': { path: 'a/b/c.md', content: 'this is content.', locals: { a: 'b' }, ext: '.md' } }, 
  '80': { 'a/b/c.md': { path: 'a/b/c.md', content: 'this is content.', ext: '.md' } }, 
  '81': { 'a/b/c.md': { path: 'a/b/c.md', content: 'this is foo', locals: { foo: 'bar' }, ext: '.md' } }, 
  '82': { 'one/two.md': { path: 'one/two.md', content: 'this is content.', data: { b: 'b' }, ext: '.md' } } 
}